### ISSUE TITLE
Can I Draw Bar Chart Combined With Line Chart?

### ISSUE THREAD

**Issue by khandar-william** [image-charts/java#1]
From your documentation, I see that you can only specify one chart type per image
https://documentation.image-charts.com/reference/chart-type/

I'm wondering is it possible to draw a bar chart with a line chart on top of it?
something like this 
![202735_Qlik sense](https://user-images.githubusercontent.com/4676896/87338177-ec509580-c56e-11ea-8d6f-3e19fb0af1cc.jpg)

**Comment by FGRibreau** [comment]
Hello!

Sorry for the delay, **yes** you can !!

That's what we call [Compound charts](https://documentation.image-charts.com/reference/markers/#creating-a-compound-chart-mixed-charts) :)

[![](https://image-charts.com/chart?chan&chd=t1%3A10%2C40%2C60%2C80%2C30%2C20%7C60%2C40%2C50%2C100%2C20%2C30&chf=b0%2Clg%2C90%2C03a9f4%2C0%2C3f51b5%2C1&chm=D%2C03a9f4%2C1%2C0%2C5%2C1&chs=978x300&cht=bvs&chxt=x%2Cy&icac=fgribreau&icretina=1&ichm=dce075bf56cd45d4e5c9301949231a301e625b09870dd75a0af57624032c1dde)](https://editor.image-charts.com/chart?chan&chd=t1%3A10%2C40%2C60%2C80%2C30%2C20%7C60%2C40%2C50%2C100%2C20%2C30&chf=b0%2Clg%2C90%2C03a9f4%2C0%2C3f51b5%2C1&chm=D%2C03a9f4%2C1%2C0%2C5%2C1&chs=978x300&cht=bvs&chxt=x%2Cy&icac=fgribreau&icretina=1&ichm=dce075bf56cd45d4e5c9301949231a301e625b09870dd75a0af57624032c1dde)

> [edit chart](https://editor.image-charts.com/chart?chan&chd=t1%3A10%2C40%2C60%2C80%2C30%2C20%7C60%2C40%2C50%2C100%2C20%2C30&chf=b0%2Clg%2C90%2C03a9f4%2C0%2C3f51b5%2C1&chm=D%2C03a9f4%2C1%2C0%2C5%2C1&chs=978x300&cht=bvs&chxt=x%2Cy&icac=fgribreau&icretina=1&ichm=dce075bf56cd45d4e5c9301949231a301e625b09870dd75a0af57624032c1dde)
